services:
  - type: web
    name: gotenberg
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CHROMIUM_DISABLE_SANDBOX
        value: "1"
    ports:
      - port: 3000
        protocol: http
