services:
  - type: web
    name: pdf-auto-generator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    autoDeploy: true
    healthCheckPath: /generate
    envVars:
      - key: PORT
        value: 5000
